### ISSUE TITLE
`GIT_DESCRIBE_TAG` on macos

### ISSUE THREAD

**Issue by xobs** [litex-hub/conda-build-prepare#8]
I'm unclear if this is a macos issue or a problem with `conda-build-prepare`, but I'm trying to build some EDA files using the recommended method and it's failing on `GIT_DESCRIBE_TAG`.

As an example, the yosys meta.yaml contains a line that looks like:

```
{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('yosys-', '') or '0.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}
```

If I export `GIT_DESCRIBE_TAG` to the output of `$(git describe --tag)`, this does not work:

```
Cloning git sources...

Cloning into '/Users/sean/Code/EDA/conda-eda/workdir/git-repos/yosys'...
remote: Enumerating objects: 71310, done.
remote: Counting objects: 100% (939/939), done.
remote: Compressing objects: 100% (454/454), done.
remote: Total 71310 (delta 612), reused 748 (delta 485), pack-reused 70371
Receiving objects: 100% (71310/71310), 23.37 MiB | 13.75 MiB/s, done.
Resolving deltas: 100% (52431/52431), done.
Already on 'master'
Modifying git tags to set proper package version...

Rewriting tags in "/Users/sean/Code/EDA/conda-eda/workdir/git-repos/yosys"...

Successfully tagged '7e588664e7efa36ff473f0497feacaad57f5e90c' object as '0.26'
Rendering package metadata, please wait...

/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:19: UserWarning: zstandard could not be imported. Running without .conda support.
  warnings.warn("zstandard could not be imported. Running without .conda support.")
/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
  _warnings.warn("Install zstandard Python bindings for .conda support")
Error: Failed to render jinja template in /Users/sean/Code/EDA/conda-eda/workdir/recipe/meta.yaml:
'GIT_DESCRIBE_TAG' is undefined

ERROR conda.cli.main_run:execute(47): `conda run conda render -f /Users/sean/Code/EDA/conda-eda/workdir/recipe/rendered_metadata.yaml /Users/sean/Code/EDA/conda-eda/workdir/recipe` failed. (See above for error)
!! =======================================================
!! ERROR: conda-build-prepare subprocess failed!
!!
!! Command called: conda run -p /Users/sean/Code/EDA/conda-eda/workdir/conda-env conda render -f /Users/sean/Code/EDA/conda-eda/workdir/recipe/rendered_metadata.yaml /Users/sean/Code/EDA/conda-eda/workdir/recipe
!!
!! STDERR not captured; look above for errors too! STDOUT:
!!
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was:
Command '['/Users/sean/Code/EDA/conda-eda/workdir/conda-env/bin/patch', '--no-backup-if-mismatch', '--batch', '-Np1', '-i', '/var/folders/w2/hfp7dn0d30590f7npsqlj1hh0000gn/T/tmpby1c76n5/makefile-conda-config.patch.native', '--binary', '--dry-run']' returned non-zero exit status 1.
!!
!! =======================================================

Error during package metadata rendering!
/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/conda_package_streaming/package_streaming.py:19: UserWarning: zstandard could not be imported. Running without .conda support.
  warnings.warn("zstandard could not be imported. Running without .conda support.")
/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/conda_package_handling/api.py:29: UserWarning: Install zstandard Python bindings for .conda support
  _warnings.warn("Install zstandard Python bindings for .conda support")

Traceback (most recent call last):
  File "/tmp/really-long-path/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/really-long-path/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/really-long-path/conda/lib/python3.10/site-packages/conda_build_prepare/__main__.py", line 54, in <module>
    prepare_recipe(recipe_dir, git_dir, env_dir)
  File "/tmp/really-long-path/conda/lib/python3.10/site-packages/conda_build_prepare/conda_cmds.py", line 375, in prepare_recipe
    meta = render_metadata(package_dir, env_dir)
  File "/tmp/really-long-path/conda/lib/python3.10/site-packages/conda_build_prepare/conda_cmds.py", line 59, in render_metadata
    _call_conda_cmd_in_env(f"conda render -f {rendered_path} {package_dir}", env_dir)
  File "/tmp/really-long-path/conda/lib/python3.10/site-packages/conda_build_prepare/conda_cmds.py", line 177, in _call_conda_cmd_in_env
    return _check_output(f'conda run -p {env_path} {cmd_string}')
  File "/tmp/really-long-path/conda/lib/python3.10/site-packages/conda_build_prepare/conda_cmds.py", line 157, in _check_output
    return subprocess.check_output(command.split(), encoding='utf-8',
  File "/tmp/really-long-path/conda/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/tmp/really-long-path/conda/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['conda', 'run', '-p', '/Users/sean/Code/EDA/conda-eda/workdir/conda-env', 'conda', 'render', '-f', '/Users/sean/Code/EDA/conda-eda/workdir/recipe/rendered_metadata.yaml', '/Users/sean/Code/EDA/conda-eda/workdir/recipe']' returned non-zero exit status 1.

sean in 🌐 Garlemald in conda-eda on  master [!?] took 33s
❯ 
```

However, if I set it to the following, I can get it to build:

```
{% set version = '0.X_0000_gUNKNOWN' %}
```

Note that I'm following the instructions at: https://github.com/hdl/conda-eda/blob/master/docs/DEVELOPMENT.md#preparing-the-recipe-with-conda-build-prepare

**Comment by ajelinski** [comment]
Neither macOS nor conda-build-prepare are to blame in this case.

The root of the problem is that `makefile-conda-config.patch` cannot be applied:
```
Command '['/Users/sean/Code/EDA/conda-eda/workdir/conda-env/bin/patch', '--no-backup-if-mismatch', '--batch', '-Np1', '-i', '/var/folders/w2/hfp7dn0d30590f7npsqlj1hh0000gn/T/tmpby1c76n5/makefile-conda-config.patch.native', '--binary', '--dry-run']' returned non-zero exit status 1.
```
(the `.native` suffix is added by Conda).

I have to admit conda-build's (the recipe is rendered with it) messages are super misleading and it's extremely common to think the problem is with the variable or `git describe`.

I think I could improve the message from conda-build-prepare to state clearly that patching failed. I won't be able to get rid of the `GIT_DESCRIBE_TAG` message since stderr isn't captured (unless it's ok to do so) but I could check if the patch command is the one that fails in the message printed to stdout.

Of course feel free to contribute if you'd like to help. 🙂

Btw. `GIT_DESCRIBE_TAG` is a Conda variable: https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#git-environment-variables so there's no easy way to override it. The git variables aren't defined if patching fails.
